# .travis.yml for FLa4a

warnings_are_errors: false

os:
  - linux

language: r
r:
  - release
  - devel

sudo: false

addons:
  apt:
    packages:
    - libgsl0-dev

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
