# .travis.yml for FLa4a

warnings_are_errors: false

os:
  - linux

language: r

r:
  - release

sudo: false

addons:
  apt:
    packages:
    - libgsl0-dev

repos:
  CRAN: https://cloud.r-project.org
  flr: http://flr-project.org/R

cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master

r_build_args: --no-build-vignettes --no-manual --no-resave-data
r_check_args: --no-build-vignettes --no-manual

script: 
  - |
    R CMD build .
    travis_wait 30 R CMD check FLa4a*tar.gz
